--- 
- hosts: all
  remote_user: root
  connection: ssh
  gather_facts: yes
  vars:
    username: admin
  tasks:
  - name: Uninstall nslookup
    # Uninstall vsftp
    yum: 
      name: vsftpd
      state: absent
